Update setting Info
hrydgard/ppsspp pull request #10416
Opened 2017-12-16 13:55 UTC by zminhquanz

Update

2017-12-16 14:42 UTC, LunaMoo commented
Breaking formatting of whole file for the sake of adding 2 questionable tips? How about not doing either?:P

2017-12-17 02:16 UTC, unknownbrackets requested changes
Would like to avoid the changes to other parts of the file, but what are you trying to clarify with these settings?

I think we could potentially make Vsync longer, just "Vsync (avoid tearing)" or something, even, if needed.  Would rather avoid the tips if we don't need to use them.

-[Unknown]

2017-12-17 02:16 UTC, unknownbrackets commented on UI/GameSettingsScreen.cpp
> +		settingInfo_->Show(gr->T("DisableSlowerEffect Tip", "Improvement performance in some scenarios on old device"));
I don't think this is a good description of what it does.  Maybe, "Make special effects look bad to improve performance".  Hopefully this is already obvious by the name?

-[Unknown]

2017-12-17 02:16 UTC, unknownbrackets commented on UI/GameSettingsScreen.cpp
> +		settingInfo_->Show(gr->T("Vsync Tip", "Avoid tearing screen , always on"));
Always on is probably confusing.  Perhaps, "Avoid screen tearing, depends on video driver"?  What are you trying to communicate here?

-[Unknown]

2017-12-17 04:15 UTC, zminhquanz commented
Ok , I will change this

2017-12-18 04:02 UTC, zminhquanz commented
@unknownbrackets I was changed that as you request

2017-12-21 12:57 UTC, zminhquanz reviewed
I update info again

2017-12-22 07:29 UTC, closed without merging

2017-12-22 07:51 UTC, unknownbrackets commented
Maybe rebase it without the other formatting changes?

-[Unknown]