Rebased: Wrap some SysMemForKernel's nids, fixing #7960
hrydgard/ppsspp pull request #12225
Opened 2019-08-08 15:25 UTC by hrydgard

This is the same as #7965, but a little reworked according to Unknowns' feedback and cleaned it up a bit.

Not tested - @sum2012 ?

2019-08-08 16:35 UTC, sum2012 commented
Not work and non windows build fail
![1](https://user-images.githubusercontent.com/2177532/62720895-9493db00-ba3d-11e9-8dc0-14debc9f2c3e.png)

2019-08-08 16:52 UTC, hrydgard commented
Oops, I'll push some fixes.

2019-08-08 18:40 UTC, hrydgard commented
What happens when you run it now @sum2012 ?

2019-08-09 13:01 UTC, sum2012 commented
Not sure why not work this time
53:01:992 user_main    E[SCEKERNEL]: Util\BlockAllocator.cpp:140 Block Allocator (08800000-0a000000) failed to allocate 1300224 (0013d700) bytes of contiguous memory

full info log: https://gist.github.com/sum2012/9d4aa74913a6ad25189514b5ac52fcb2
full debug log: https://gist.github.com/sum2012/d7132ff5fd9c7bee4d43d3c2775242d8

2019-08-09 13:12 UTC, hrydgard commented
Yeah I don't understand why it would be different than before either...

2019-08-09 13:44 UTC, sum2012 commented
Do our change is really same with JPCSP change 's functionally ?
https://github.com/jpcsp/jpcsp/commit/3c25717e04c66a1f5a93e0cacc2c232ecf2d2453

2019-08-10 08:16 UTC, hrydgard commented
As far as I can tell it looks similar enough. Something else might have changed how much memory we allocate from the user pool resulting in this one failing. Just for kicks, you could try to have it allocate from kernel instead and see if things work then?

2019-08-10 09:55 UTC, sum2012 commented
How to allocate memory from kernel

2019-08-10 12:45 UTC, sum2012 commented
u32 addr = userMemory.Alloc(allocSize, frombottom, "SysMemForKernel-Heap");
change to
u32 addr = kernelMemory.Alloc(allocSize, frombottom, "SysMemForKernel-Heap");

raise another error
![2](https://user-images.githubusercontent.com/2177532/62821985-d0e74880-bbaf-11e9-96d8-d96ddcf7166e.png)

2019-08-10 14:52 UTC, unknownbrackets requested changes

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +const bool frombottom = false;
static?

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +	heap->name = *Name;
Might need some validation in case nullptr?

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +		return hleLogSuccessInfoX(SCEKERNEL, addr, "");
I usually leave the string part off for success.

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +		ERROR_LOG(HLE, "sceKernelAllocHeapMemory(%d): cannot find heapId", heapId);
Maybe would be better to use `hleLogError(SCEKERNEL, error, "cannot find heapId")`.

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +		ERROR_LOG(HLE, "sceKernelCreateHeap(partitionId=%d): Failed to allocate %d bytes memory", partitionId, size);
nit: HLE, also hleLogError?

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +	{ 0X636C953B, &WrapI_II<sceKernelAllocHeapMemory>, "sceKernelAllocHeapMemory", 'I', "ii" },
These parameter types look wrong.  Return here should be x, delete should return i (not 64 bit), and create should return i or else the first two should take x as the first param.  Flags maybe should be x.

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelHeap.cpp
> +		ERROR_LOG(HLE, "sceKernelDeleteHeap(%d): invalid heapId", heapId);
nit: HLE, hleLogError?

-[Unknown]

2019-08-10 14:52 UTC, unknownbrackets commented on Core/HLE/sceKernelThread.h
> +int sceKernelCreateHeap(int partitionId, int size, int flags, const char *Name);
It seems weird for these to be in this header file?

-[Unknown]

2020-04-26 09:36 UTC, hrydgard commented
Finally got around to addressing the last feedback, gonna get it in shortly.

2020-04-26 10:39 UTC, merged

2020-11-28 08:56 UTC, Askmewho commented
I am experiencing a similar issue on master compilation..could be related to the driver??
here on linux on arm.
@hrydgard 

```
pi@RK3399:~/Games/ppsspp$ ./PPSSPPSDL 
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 2
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
Surface extension not found
DEBUG: Vulkan is not available, not using Vulkan.
Info: We compiled against SDL version 2.0.10 and we are linking against SDL version 2.0.10. :)
27:41:136 Core/Config.cpp:540 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
Pixels: 960 x 544
Virtual pixels: 960 x 544
ERROR: EGL Error EGL_BAD_ALLOC detected in file /media/pi/Linux/RK3399/ppsspp/SDL/SDLGLGraphicsContext.cpp at line 264 (0x3003)
EGL ERROR: Unable to create EGL surface!
EGL_Init() failed
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
27:53:944 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
27:54:489 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0125 - Midnight Club 3 - DUB Edition (Europe) (En,Fr,De,Es,It) (v1.02).iso...
27:54:848 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
27:56:008 sceMemab     E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
27:56:008 sceMemab     E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
28:03:186 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(321): bad thread
28:03:187 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(323): bad thread
28:03:187 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(322): bad thread
28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(332): bad thread
28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(334): bad thread
28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(333): bad thread
28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(342): bad thread
28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(344): bad thread
28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(343): bad thread
31:30:819 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
31:31:197 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0411 - OutRun 2006 - Coast 2 Coast (USA) (v1.03).iso...
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
31:32:200 user_main    E[SCEIO]: HLE/sceIo.cpp:1970 UNIMPL sceIoDevctl("usbpspcm:", 03415001, 09fff610, 4, 00000000, 0)
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
32:17:882 user_main    E[SCEIO]: HLE/sceIo.cpp:1970 UNIMPL sceIoDevctl("usbpspcm:", 03415002, 08bf5b08, 4, 00000000, 0)
32:17:883 user_main    E[SCEMODULE]: HLE/sceKernelModule.cpp:2160 sceKernelStopModule(0000014b, 00000000, 00000000, 00000000, 00000000): invalid module id
32:17:883 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2336 sceKernelTerminateDeleteThread(330): thread doesn't exist
33:09:855 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
33:10:425 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0346 - Daxter (USA).iso...
33:10:794 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0xdde0_size0x60b3' with write access on an ISO partition
33:10:794 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0xdde0_size0x60b3, 3, 0)
33:10:816 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
33:10:816 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
33:10:819 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x1a370_size0x102fe4' with write access on an ISO partition
33:10:820 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x1a370_size0x102fe4, 3, 0)
33:10:845 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x195b0_size0x825c0' with write access on an ISO partition
33:10:845 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x195b0_size0x825c0, 3, 0)
33:19:178 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x165a0_size0x3bd4a0' with write access on an ISO partition
33:19:178 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x165a0_size0x3bd4a0, 3, 0)
33:19:410 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x1de50_size0x2a5b38' with write access on an ISO partition
33:19:410 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x1de50_size0x2a5b38, 3, 0)
33:28:476 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x12d30_size0x481cfc' with write access on an ISO partition
33:28:476 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x12d30_size0x481cfc, 3, 0)
33:29:057 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 335
33:29:058 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x24320_size0x312a0' with write access on an ISO partition
33:29:058 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x24320_size0x312a0, 3, 0)
33:30:392 user_main    E[ME]: HLE/sceMpeg.cpp:1351 UNIMPL sceMpegAvcDecodeFlush(08bd187c)
33:30:491 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
33:30:491 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
34:03:413 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 360
34:03:447 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x239e0_size0x30880' with write access on an ISO partition
34:03:447 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x239e0_size0x30880, 3, 0)
34:04:534 user_main    E[ME]: HLE/sceMpeg.cpp:1351 UNIMPL sceMpegAvcDecodeFlush(08bd187c)
34:04:618 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
34:04:618 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
34:08:781 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 375
34:08:806 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x24a20_size0x30530' with write access on an ISO partition
34:08:806 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x24a20_size0x30530, 3, 0)
34:09:790 user_main    E[ME]: HLE/sceMpeg.cpp:1351 UNIMPL sceMpegAvcDecodeFlush(08bd187c)
34:09:906 user_main    E[FILESYS]: FileSystem [...]

2020-11-28 09:03 UTC, sum2012 commented
Can you change to info log?

在 2020年11月28日週六 下午4:57，Askmewho <notifications@github.com> 寫道：

> I am experiencing a similar issue on master compilation..could be related
> to the driver??
> here on linux on arm.
> @hrydgard <https://github.com/hrydgard>
>
> pi@RK3399:~/Games/ppsspp$ ./PPSSPPSDL
> VulkanMayBeAvailable: Device allowed ('SDL:Linux')
> VulkanMayBeAvailable: Library loaded ('libvulkan.so')
> VulkanMayBeAvailable: Enumerating instance extensions
> VulkanMayBeAvailable: Instance extension count: 2
> VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
> VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
> Surface extension not found
> DEBUG: Vulkan is not available, not using Vulkan.
> Info: We compiled against SDL version 2.0.10 and we are linking against SDL version 2.0.10. :)
> 27:41:136 Core/Config.cpp:540 I[G3D]: Longest display side: -1 pixels. Choosing scale 1
> Pixels: 960 x 544
> Virtual pixels: 960 x 544
> ERROR: EGL Error EGL_BAD_ALLOC detected in file /media/pi/Linux/RK3399/ppsspp/SDL/SDLGLGraphicsContext.cpp at line 264 (0x3003)
> EGL ERROR: Unable to create EGL surface!
> EGL_Init() failed
> loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
> 27:53:944 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
> 27:54:489 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0125 - Midnight Club 3 - DUB Edition (Europe) (En,Fr,De,Es,It) (v1.02).iso...
> 27:54:848 user_main    E[FILESYS]: FileSystems/DirectoryFileSystem.cpp:62 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
> 27:56:008 sceMemab     E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 27:56:008 sceMemab     E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 28:03:186 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(321): bad thread
> 28:03:187 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(323): bad thread
> 28:03:187 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(322): bad thread
> 28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(332): bad thread
> 28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(334): bad thread
> 28:11:544 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(333): bad thread
> 28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(342): bad thread
> 28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(344): bad thread
> 28:21:250 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2783 sceKernelSuspendThread(343): bad thread
> 31:30:819 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
> 31:31:197 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0411 - OutRun 2006 - Coast 2 Coast (USA) (v1.03).iso...
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
> 31:32:200 user_main    E[SCEIO]: HLE/sceIo.cpp:1970 UNIMPL sceIoDevctl("usbpspcm:", 03415001, 09fff610, 4, 00000000, 0)
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
> 31:32:200 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
> 32:17:882 user_main    E[SCEIO]: HLE/sceIo.cpp:1970 UNIMPL sceIoDevctl("usbpspcm:", 03415002, 08bf5b08, 4, 00000000, 0)
> 32:17:883 user_main    E[SCEMODULE]: HLE/sceKernelModule.cpp:2160 sceKernelStopModule(0000014b, 00000000, 00000000, 00000000, 00000000): invalid module id
> 32:17:883 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2336 sceKernelTerminateDeleteThread(330): thread doesn't exist
> 33:09:855 HLE/sceNet.cpp:210 N[SCENET]: LocalHost IP will be 127.0.0.1 [b7:a5:8d:da:12:58]
> 33:10:425 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0346 - Daxter (USA).iso...
> 33:10:794 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0xdde0_size0x60b3' with write access on an ISO partition
> 33:10:794 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0xdde0_size0x60b3, 3, 0)
> 33:10:816 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
> 33:10:816 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
> 33:10:819 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x1a370_size0x102fe4' with write access on an ISO partition
> 33:10:820 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x1a370_size0x102fe4, 3, 0)
> 33:10:845 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x195b0_size0x825c0' with write access on an ISO partition
> 33:10:845 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x195b0_size0x825c0, 3, 0)
> 33:19:178 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x165a0_size0x3bd4a0' with write access on an ISO partition
> 33:19:178 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x165a0_size0x3bd4a0, 3, 0)
> 33:19:410 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x1de50_size0x2a5b38' with write access on an ISO partition
> 33:19:410 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x1de50_size0x2a5b38, 3, 0)
> 33:28:476 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x12d30_size0x481cfc' with write access on an ISO partition
> 33:28:476 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x12d30_size0x481cfc, 3, 0)
> 33:29:057 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 335
> 33:29:058 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x24320_size0x312a0' with write access on an ISO partition
> 33:29:058 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x24320_size0x312a0, 3, 0)
> 33:30:392 user_main    E[ME]: HLE/sceMpeg.cpp:1351 UNIMPL sceMpegAvcDecodeFlush(08bd187c)
> 33:30:491 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
> 33:30:491 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
> 34:03:413 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 360
> 34:03:447 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x239e0_size0x30880' with write access on an ISO partition
> 34:03:447 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x239e0_size0x30880, 3, 0)
> 34:04:534 user_main    E[ME]: HLE/sceMpeg.cpp:1351 UNIMPL sceMpegAvcDecodeFlush(08bd187c)
> 34:04:618 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x242a0_size0x39e70' with write access on an ISO partition
> 34:04:618 user_main    E[SCEIO]: HLE/sceIo.cpp:1501 8001b004=sceIoOpen(disc0:/sce_lbn0x242a0_size0x39e70, 3, 0)
> 34:08:781 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:1243 __KernelGetWaitID ERROR: thread 375
> 34:08:806 user_main    E[FILESYS]: FileSystems/ISOFileSystem.cpp:340 Can't open file '/sce_lbn0x24a20_size0x30530' with write ac [...]

2020-11-28 22:36 UTC, Askmewho commented
It will not say anything different.
Do I need to recompile it to debug?
the games are not crashing, just nore performing great, 
but maybe this isnt the problem of that. it doesnt happen on all the games.
[infolog.zip](https://github.com/hrydgard/ppsspp/files/5611326/infolog.zip)
@sum2012

2020-11-28 22:42 UTC, sum2012 commented
Did you really changed these log channel to "Info" ?
![1](https://user-images.githubusercontent.com/2177532/100527495-f7e6e500-320d-11eb-9b1a-e4bc9cb27ec1.png)

2020-11-28 22:47 UTC, Askmewho commented
ohh Sorry!! wait a sec

2020-11-28 22:54 UTC, sum2012 commented
you do not need recompile

在 2020年11月29日週日 上午6:47，Askmewho <notifications@github.com> 寫道：

> ohh Sorry!! wait a sec
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hrydgard/ppsspp/pull/12225#issuecomment-735300537>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQTT7F2SYAOFGZQKBBDG2DSSF4ZRANCNFSM4IKLV5RQ>
> .
>

2020-11-29 05:39 UTC, Askmewho commented
did you see any fixable thing on my last log post? maybe it's my kernel. @sum2012

2020-11-29 10:05 UTC, sum2012 commented
@Askmewho Why I do not see this line in your newest long ?
sceMemab     E[HLE]: HLE/HLE.cpp:666 Unknown syscall: Module: (unknown) (module: 255 func: 4095)

2020-11-29 10:13 UTC, Askmewho commented
mmm no idea. does it matter? I will make a new one

2020-11-29 11:05 UTC, sum2012 commented
@Askmewho Yes,we might be still some kernel module that do not implement

2020-11-29 11:12 UTC, Askmewho commented
I am worried about the memory access warnings. those should have performance penalties? how the emulator can avoid such a problem?

2020-11-29 11:17 UTC, sum2012 commented
I know now, you load 2 different game.

The first one:
27:54:489 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0125 - Midnight Club 3 - DUB Edition (Europe) (En,Fr,De,Es,It) (v1.02).iso...


The second one:
29:51:999 root         N[BOOT]: UI/EmuScreen.cpp:301 Loading /media/pi/Externo/ROMS/PSP/0346 - Daxter (USA).iso

I need the first one game (0125 - Midnight Club 3 - DUB Edition (Europe) (En,Fr,De,Es,It) (v1.02).iso.) 's info log

2020-11-29 11:54 UTC, sum2012 commented
My friend dump the game to me .
In-game no problem.The game might not be multi player play becuase It is missing network module .
I will open another issue for it
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,482cae9a) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,c9a8cab7) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,5baa1fe5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,2d0fae4e) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceWlanDrv_lib,56f467ca) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,5216cbf5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:637 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d2422e4d) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d1be2ce9) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,ab7dd9a5) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,7ba3ed91) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,03164b12) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,389728ab) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,d5b64e37) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,da02f383) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,afa11338) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,b20f84f8) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,a55c914f) unresolved in 'sceNetAdhocctl_Library', storing for later resolving
47:03:638 user_main    I[LOADER]: hle\scekernelmodule.cpp:779 Function (sceNet_lib,0d633f53) unresolved in 'sceNetAdhocctl_Library', storing for later resolving

2020-11-29 12:33 UTC, sum2012 commented
@Askmewho  What are you doing in playing "Midnight Club 3 - DUB Edition" ?
I do not see  "failed to allocate" log in my log