Fix GCC9 Crash
hrydgard/ppsspp pull request #13920
Opened 2021-01-15 13:15 UTC by liberodark

2021-01-15 14:13 UTC, hrydgard commented
That's interesting. Does the crash also go away if you turn optimization down to -O2? 

I don't really know why we use -O3 anyway, it's not likely to be a large boost.

2021-01-15 14:29 UTC, liberodark commented
This problem is on some SBCs.
Personally I haven't used -O2 but I think one of my colleagues there already did.

2021-01-15 15:25 UTC, orbea commented
> I don't really know why we use -O3 anyway, it's not likely to be a large boost.

Using `-O3` can expose experimental features in compilers, the safer default is `-O2`.

2021-01-15 15:33 UTC, orbea requested changes

2021-01-15 15:33 UTC, orbea commented on CMakeLists.txt
> +	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -fno-tree-slp-vectorize -D_NDEBUG")
This is the wrong place for compiler flags and it should be tested during configure if the compiler actually supports it.

I also suspect this doesn't fix the root issue which is probably undefined behavior in ppsspp or a compiler bug.

2021-01-15 16:58 UTC, orbea commented
@liberodark I would suggest you spend some time narrowing this down so a better fix or more specific workaround can be found. 

First set `-fno-tree-slp-vectorize` for every file and then remove the flag for half off them, then repeat until its narrowed down to specific file(s). Next disable it with a gcc pragma until it narrowed down to specific code which may be in the included headers.

For example here was an old workaround for a now fixed gcc7 bug.

https://github.com/libretro/bsnes-mercury/pull/50/files

And when it was fixed in gcc.

https://github.com/libretro/bsnes-mercury/pull/71/files

2021-01-17 09:38 UTC, rtissera commented
We had a ppsspp crash with O3 GCC 9.3.0 on some ARM devices (RK3326 at least) on PPSSPP for batocera.linux 

I bissected all individual flags between O2 to O3 to narrow down the problematic optimization at a global level.

2021-01-17 09:42 UTC, hrydgard commented
Well, now that you have narrowed down the optimization, it would be even more useful if you could narrow it down to the file. It could be a bug in PPSSPP, just as well as it could be an optimizer bug.

But I think I'm just gonna bump it down to -O2.

2021-01-17 09:43 UTC, rtissera commented
Ok let me some time to find down in our git history the affected platform
and games to reproduce and get a better scope of the issue.

Le dim. 17 janv. 2021 à 10:42, Henrik Rydgård <notifications@github.com> a
écrit :

> Well, now that you have narrowed down the optimization, it would be even
> more useful if you could narrow it down to the file. It could be a bug in
> PPSSPP, just as well as it could be an optimizer bug.
>
> But I think I'm just gonna bump it down to -O2.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/hrydgard/ppsspp/pull/13920#issuecomment-761762281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW4WBN7CTE67OZ7N2LNQQLS2KWH3ANCNFSM4WEBIARA>
> .
>

2021-02-21 18:21 UTC, unknownbrackets commented
Had any luck narrowing this down to specific files or groups thereof?

-[Unknown]

2021-07-09 20:51 UTC, hrydgard commented
Is this still an issue?

Can you get a backtrace of the crash?

2021-11-09 22:11 UTC, hrydgard commented
No feedback in quite a while, closing.

2021-11-09 22:11 UTC, closed without merging