[Adhoc] Fix multiplayer issue on MGS:PW due to detecting an incorrect source port on incoming data
hrydgard/ppsspp pull request #14140
Opened 2021-02-14 10:53 UTC by ANR2ME

Fix multiplayer issue on MGS:PW due to detecting an incorrect source port on incoming data
May not be the best solution since i haven't really figured out what actually happening, but fix #14130 most of the time, although i'm still getting a wrong port detected once but seems to happen very rarely now.

PS: In the case AdhocMatching detecting an incorrect port, players will see an orange message on screen saying "Data from incorrect Port detected [MAC address]: SourcePort -> DestPort" where SourcePort is the wrong one and supposed to be the same with DestPort.

If this message appeared, players just need to wait until the port detected correctly (may takes a few seconds or more before it gets detected correctly), otherwise progressing any further will cause communication issue.

2021-02-14 14:05 UTC, MojoJojoDojo commented
Won't all the delays in the code cause more desyncs?
Because its already happening even in localhost with some games if you play for some time.

2021-02-14 14:08 UTC, ANR2ME commented
It's only delayed when creating the socket, most games doesn't create new socket during game play

2021-02-15 08:24 UTC, sum2012 requested changes

2021-02-15 08:24 UTC, sum2012 commented on Core/HLE/sceNetAdhoc.cpp
> +                    host->NotifyUserMessage(std::string("Data from incorrect Port detected [") + mac2str(&sendermac) + std::string("]:") + std::to_string(senderport) + std::string(" -> ") + std::to_s
Add translate of "Data from incorrect Port detected"

2021-02-15 15:18 UTC, ANR2ME commented
Updated with translate

2021-02-15 20:38 UTC, sum2012 approved these changes

2021-02-16 09:10 UTC, ANR2ME commented
Looks like MGS:PW versus mode still have the incorrect port issue :(
![image](https://user-images.githubusercontent.com/7974720/108041663-6a2ecf00-7071-11eb-8483-e955b473a9e8.png)
And it doesn't seems to be disappearing over time :(

2021-02-21 10:27 UTC, ANR2ME commented
Okay this seems to fix the issue some how... can't find any documentation on such `bind` behavior tho.

2021-02-21 10:56 UTC, hrydgard commented on Core/HLE/sceNetAdhoc.cpp
> +                    host->NotifyUserMessage(std::string(n->T("Data from incorrect Port")) + std::string(" [") + mac2str(&sendermac) + std::string("]:") + std::to_string(senderport) + std::string(" ->
wacky indentation here :)

2021-02-21 13:07 UTC, ANR2ME commented on Core/HLE/sceNetAdhoc.cpp
> +                    host->NotifyUserMessage(std::string(n->T("Data from incorrect Port")) + std::string(" [") + mac2str(&sendermac) + std::string("]:") + std::to_string(senderport) + std::string(" ->
oops sorry

2021-02-21 17:56 UTC, hrydgard commented
Ready to go?

2021-02-21 20:33 UTC, ANR2ME commented
yes, i think so.

2021-02-21 21:18 UTC, merged

2021-05-10 05:59 UTC, ANR2ME commented
Note: Apparently "Data from incorrect port" message can also occurred on Windows vs Windows http://forums.ppsspp.org/showthread.php?tid=27580

2021-07-24 19:57 UTC, MojoJojoDojo commented
I have one guy on Android that keeps getting me to get the incorrect port error every time.
Every game we tried got this result which is strange because I thought this happens on certain games only.
The only game that is not affected is a game that does not use AdhocMatching (Socom Fireteam bravo 3).

2021-07-24 22:52 UTC, ANR2ME commented
The wrong source port issue happened on PDP socket which is connection-less (not sure about PTP, since it connection-oriented it probably didn't matter as long it can get connected), and AdhocMatching is using PDP under-the-hood, so i only shows the error message on games that use AdhocMatching because i know on AdhocMatching both side (host & client) should use the same port for communication.

So games that doesn't use AdhocMatching but use PDP socket might also have similar issue but not being reported/shown, because we don't know which port it supposed to came from as it varies on each game, and not all game use the same port for sending and receiving.

PS: This PR probably didn't solve this issue yet and i'm planning to remove some part of of the code which may not be useful (ie. trying to send an empty data to port 0 hoping for the socket to be bound to the correct interface sooner)