Indonesian translation
hrydgard/ppsspp pull request #15077
Opened 2021-10-31 23:04 UTC by unknownbrackets

This was sent to me, so just opening a pull request here.

-[Unknown]

2021-10-31 23:40 UTC, PutuDesca commented
I have finished the Indonesian translation 

id_ID.ini (fixed): https://www.mediafire.com/download/fcukh2k9c7jxjfs

2021-10-31 23:43 UTC, PutuDesca commented
[Audio]
Alternate speed volume = Kecepatan volume alternatif
Audio backend = Latar belakang audio (perlu mulai ulang)
Audio Error = Kesalahan audio
AudioBufferingForBluetooth = Penyangga bluetooth (lambat)
Auto = Otomatis
Device = Perangkat
Disabled = Nonaktif
DSound (compatible) = DSound (kompatibel)
Enable Sound = Aktifkan suara
Global volume = Volume global
Microphone = Mikrofon
Microphone Device = Mikrofon perangkat
Mute = Tidak bersuara
Reverb volume = Volume gema
Use new audio devices automatically = Gunakan perangkat audio baru secara otomatis
Use global volume = Gunakan volume global
WASAPI (fast) = WASAPI (cepat)

[Controls]
Analog Axis Sensitivity = Sensitivitas sumbu analog
Analog Binding = Pengikatan analog
Analog Limiter = Pembatas analog
Analog Mapper High End = Pemetaan analog kelas atas (sensitivitas sumbu)
Analog Mapper Low End = Pemetaan analog kelas bawah (zona mati terbalik)
Analog Mapper Mode = Mode pemetaan analog
Analog Settings = Pengaturan analog
Analog Stick = Stik analog
Analog Style = Gaya analog
AnalogLimiter Tip = Ketika tombol pembatas analog ditekan
Auto = Otomatis
Auto-centering analog stick = Penengahan otomatis stik analog
Auto-hide buttons after seconds = Sembunyikan tombol setelah beberapa detik
Auto-rotation speed = Kecepatan rotasi otomatis
Auto-switch = Pengalihan otomatis
Base tilt position = Posisi kemiringan dasar
Binds = Pengikat
Button Binding = Pengikat tombol
Button Opacity = Kegelapan tombol
Button style = Gaya tombol
Calibrate Analog Stick = Kalibrasi stik analog
Calibrate D-Pad = Kalibrasi D-Pad
Calibrated = Dikalibrasi
Calibration = Kalibrasi
Circular stick input = Masukan stik melingkar
Classic = Klasik
Combo Key Setting = Pengaturan tombol kombinasi
Combo Key Setup = Konfigurasi tombol kombinasi
Confine Mouse = Kunci mouse di area layar
Control Mapping = Pemetaan kontrol
Custom Key Setting = Pengaturan kunci kustom
Customize = Sesuaikan
Customize Touch Controls = Sesuaikan tata letak kontrol sentuh
Customize tilt = Sesuaikan kemiringan
D-PAD = D-Pad
Deadzone radius = Radius mati
DInput Analog Settings = Pengaturan analog DInput
Disable D-Pad diagonals (4-way touch) = Matikan D-Pad diagonal (sentuhan 4 arah)
Disable diagonal input = Nonaktifkan masukan diagonal
Double tap = Ketuk dua kali
Enable gesture control = Aktifkan kontrol gerakan
Enable standard shortcut keys = Aktifkan tombol pintas standar
Gesture = Gerak
Gesture mapping = Pemetaan gerakan
Glowing borders = Pinggiran bercahaya
HapticFeedback = Umpan balik (getar)
Hide touch analog stick background circle = Sembunyikan lingkaran latar belakang tongkat analog sentuh
Icon = Ikon
Ignore gamepads when not focused = Abaikan gamepad saat tidak fokus
Ignore Windows Key = Abaikan tombol Windows
Invert Axes = Balikkan sumbu
Invert Tilt along X axis = Balikkan kemiringan sepanjang sumbu X
Invert Tilt along Y axis = Balikkan kemiringan sepanjang sumbu Y
Keep this button pressed when right analog is pressed = Terus tekan tombol ini saat analog kanan ditekan
Keyboard = Papan ketik
L/R Trigger Buttons = Tombol pemicu L/R
Landscape = Lanskap
Landscape Auto = Lanskap otomatis
Landscape Reversed = Lanskap terbalik
Low end radius = Radius kelas atas
Mouse = Pengaturan Mouse
Mouse sensitivity = Sentivitas Mouse
Mouse smoothing = Kehalusan Mouse
MouseControl Tip = Anda sekarang dapat memetakan mouse di layar pemetaan kontrol dengan menekan ikon 'M'.
None (Disabled) = Tidak ada (nonaktif)
Off = Mati
OnScreen = Kontrol sentuh di layar
Portrait = Tegak
Portrait Reversed = Tegak terbalik
PSP Action Buttons = Tombol aksi PSP
Raw input = Masukan mentah
Reset to defaults = Setel ulang ke pengaturan awal
Screen aligned to ground = Layar sejajar kebawah
Screen at right angle to ground = Layar pada sudut kanan kebawah
Screen Rotation = Rotasi layar
seconds, 0 : off = detik, 0 = mati
Sensitivity (scale) = Sensivitas (skala)
Sensitivity = Sensitivitas
Shape = Membentuk/bentuk
Show right analog = Tampilkan analog kanan
Show Touch Pause Menu Button = Tampilkan tombol menu jeda
Swipe = Geser
Swipe sensitivity = Geser sensivitas
Swipe smoothing = Geser kehalusan
Thin borders = Garis batas tipis
Tilt Base Radius = Radius kemiringan dasar
Tilt Input Type = Jenis masukan kemiringan
Tilt Sensitivity along X axis = Sensitivitas kemiringan sepanjang sumbu X
Tilt Sensitivity along Y axis = Sensitivitas kemiringan sepanjang sumbu Y
To Calibrate = Untuk mengkalibrasi, taruh perangkat di permukaan datar dan tekan "Kalibrasi".
Toggle mode = Mode beralih
Touch Control Visibility = Visibilitas kontrol sentuh
Use custom right analog = Gunakan analog kanan kustom
Use Mouse Control = Gunakan kontrol mouse
Visibility = Visibilitas
Visible = Visibel
X = X
X + Y = X + Y
XInput Analog Settings = Pengaturan analog XInput
Y = Y

[CwCheats]
Cheats = Pengecoh
Edit Cheat File = Edit berkas pengecoh
Enable/Disable All = Hidupkan/matikan semua pengecoh
Import Cheats = Impor dari cheat.db
Options = Pilihan
Refresh Rate = Perbarui Penyegaran

[DesktopUI]
# If your language does not show well with the default font, you can use Font to specify a different one.
# Just add it to your language's ini file and uncomment it (remove the # by Font).
#Font = Trebuchet MS
About PPSSPP... = Tent&ang PPSSPP...
Auto = Otomatis
Auto Max Quality = Otomatis kualitas maksimum
Backend = Bangun Pelukisan &Bagian belakang  (Mulai ulang PPSSPP)
Bicubic = &Bikubik
Break = Rusak
Break on Load = Rusak pada pemuatan
Buffered Rendering = Pelukisan Tersangga
Buy Gold = Beli versi &Gold
Control Mapping... = Pemetaan K&ontrol...
Debugging = Awakutu
Deposterize = &Deposterisasi
Direct3D9 = &Direct3D9
Direct3D11 = Direct3D11
Disassembly = &Pembongkaran...
Discord = Discord
Display Layout Editor = Penyunting tata letak tampilan...
Display Rotation = Rotasi tampilan
Dump Next Frame to Log = B&uang Laju Bingkai Berikutnya untuk Masuk
Emulation = &Emulasi
Enable Chat = Aktifkan pesan
Enable Cheats = Hidupkan Penge&coh
Enable Sound = Hidupkan Suara
Exit = Keluar
Extract File... = Ekstrak Berkas...
File = Berkas
Frame Skipping = &Lewati Laju Bingkai
Frame Skipping Type = Jenis Lewati Laju Bingkai
Fullscreen = &Layar Penuh
Game Settings = Pengaturan Permainan
GE Debugger... = Awakutu GE...
GitHub = Git&Hub
Hardware Transform = Transformasi Perangkat Keras
Help = Bantuan
Hybrid = &Hibrida
Hybrid + Bicubic = Hibrida + Bikubik
Ignore Illegal Reads/Writes = Aba&ikan Pembacaan/Penulisan Ilegal
Ignore Windows Key = Abaikan Tombol Windows
Keep PPSSPP On Top = Tahan PPSSPP di Atas
Landscape = Lanskap
Landscape reversed = Lanskap terbalik
Language... = Bahasa...
Linear = &Linier
Load = Muat...
Load .sym File... = Mu&at Berkas .sym...
Load Map File... = Muat Berkas &Map...
Load State = L&oad State
Load State File... = &Load State File...
Log Console = Konso&l Pencatat
Memory View... = Tampilan Memori...
More Settings... = Pengaturan Lainnya...
Nearest = Terdekat
Non-Buffered Rendering = Lewati efek penyangga (tak-tersangga, lebih cepat)
Off = Mati
Open Chat = Buka opsi pesan
Open Directory... = Buka &Direktori...
Open from MS:/PSP/GAME... = Buka dari MS:/PSP/GAME...
Open Memory Stick = Buka &Memory Stick
Open New Instance = Buka contoh baru
OpenGL = &OpenGL
Pause = Jeda
Pause When Not Focused = Jeda Ketika Tidak Fokus
Portrait = Tegak
Portrait reversed = Tegak terbalik
Postprocessing Shader = Postprocessin&g Shader
PPSSPP Forums = &Forum PPSSPP
Record = Rekam
Record Audio = Rekam Suara
Record Display = Rekam Tampilan
Rendering Mode = M&ode Pelukisan
Rendering Resolution = &Resolusi Pelukisan
Reset = Atur Ulang
Reset Symbol Table = Atur Ulang Tabel Simbol
Run = Jalankan
Save .sym File... = Simpan B&erkas .sym...
Save Map File... = &Simpan Berkas Peta...
Save State = Simp&an Posisi
Save State File... = &Simpan Berkas Posisi...
Savestate Slot = Simp&an Status Slot
Screen Scaling Filter = Penyaring P&enskala Layar
Show Debug Statistics = Tampilkan Statistik Awakutu
Show FPS Counter = Tampilkan Penghitung &FPS
Skip Number of Frames = Lewati nomor laju bing [...]

2021-11-01 00:13 UTC, PutuDesca commented
Alternative link id_ID.ini:

https://www.mediafire.com/download/fcukh2k9c7jxjfs

2021-11-01 00:46 UTC, PutuDesca requested changes
The incorrect line (string) has been replaced

2021-11-01 00:51 UTC, PutuDesca commented
Ok, i finished fixing it

New link: https://www.mediafire.com/download/q54i7qzt2qogznq

2021-11-01 09:24 UTC, merged

2021-11-01 11:55 UTC, PutuDesca requested changes
let me correct the translation a bit

2021-11-01 12:01 UTC, hrydgard commented
Just send in your new translation. If you don't know how to open a pull request, just make an issue here and attach (drag into the text) your translation in a zip file.

2021-11-01 12:03 UTC, PutuDesca commented
on line 799 it should be written "letak port (0 = kecocokan dengan PSP)"

on line 799 it should be written "Aktifkan pesan jaringan"

on line 799 it should be written "Gelombang"

2021-11-01 12:06 UTC, PutuDesca commented
on line 799 it should be written "port location (0 = compatibility with PSP)" 

on line 776 it should be written "Enable network messages" 

on line 1188 it should be written "Gelombang"

2021-11-01 12:07 UTC, PutuDesca commented
on line 799 it should be written "letak port (0 = kecocokan dengan PSP)"

on line 776 it should be written "Aktifkan pesan jaringan"

on line 1188 it should be written "Gelombang"

2021-11-01 12:15 UTC, PutuDesca commented
On line 478 it should be "Penata Grafis"

On line 137 it should be "Bangun Pelukisan &Penata Grafis (Mulai ulang PPSSPP)

2021-11-01 12:38 UTC, PutuDesca requested changes
id_ID.ini indonesia translation has been updated

New link id_ID.ini (fixed translation)
https://www.mediafire.com/download/clhbo9bk7obxsdc

2021-11-01 12:39 UTC, PutuDesca commented
Fixed translation 
https://www.mediafire.com/download/clhbo9bk7obxsdc

2021-11-01 13:27 UTC, PutuDesca commented
id_ID.ini indonesia translation has been updated

New link id_ID.ini (fixed translation)
https://www.mediafire.com/download/clhbo9bk7obxsdc

2021-11-01 13:45 UTC, PutuDesca commented
[Audio]
Alternate speed volume = Kecepatan volume alternatif
Audio backend = Latar belakang audio (perlu mulai ulang)
Audio Error = Kesalahan audio
AudioBufferingForBluetooth = Penyangga bluetooth (lambat)
Auto = Otomatis
Device = Perangkat
Disabled = Nonaktif
DSound (compatible) = DSound (kompatibel)
Enable Sound = Aktifkan suara
Global volume = Volume global
Microphone = Mikrofon
Microphone Device = Mikrofon perangkat
Mute = Tidak bersuara
Reverb volume = Volume gema
Use new audio devices automatically = Gunakan perangkat audio baru secara otomatis
Use global volume = Gunakan volume global
WASAPI (fast) = WASAPI (cepat)

[Controls]
Analog Axis Sensitivity = Sensitivitas sumbu analog
Analog Binding = Pengikatan analog
Analog Limiter = Pembatas analog
Analog Mapper High End = Pemetaan analog kelas atas (sensitivitas sumbu)
Analog Mapper Low End = Pemetaan analog kelas bawah (zona mati terbalik)
Analog Mapper Mode = Mode pemetaan analog
Analog Settings = Pengaturan analog
Analog Stick = Stik analog
Analog Style = Gaya analog
AnalogLimiter Tip = Ketika tombol pembatas analog ditekan
Auto = Otomatis
Auto-centering analog stick = Penengahan otomatis stik analog
Auto-hide buttons after seconds = Sembunyikan tombol setelah beberapa detik
Auto-rotation speed = Kecepatan rotasi otomatis
Auto-switch = Pengalihan otomatis
Base tilt position = Posisi kemiringan dasar
Binds = Pengikat
Button Binding = Pengikat tombol
Button Opacity = Kegelapan tombol
Button style = Gaya tombol
Calibrate Analog Stick = Kalibrasi stik analog
Calibrate D-Pad = Kalibrasi D-Pad
Calibrated = Dikalibrasi
Calibration = Kalibrasi
Circular stick input = Masukan stik melingkar
Classic = Klasik
Combo Key Setting = Pengaturan tombol kombinasi
Combo Key Setup = Konfigurasi tombol kombinasi
Confine Mouse = Kunci mouse di area layar
Control Mapping = Pemetaan kontrol
Custom Key Setting = Pengaturan kunci kustom
Customize = Sesuaikan
Customize Touch Controls = Sesuaikan tata letak kontrol sentuh
Customize tilt = Sesuaikan kemiringan
D-PAD = D-Pad
Deadzone radius = Radius mati
DInput Analog Settings = Pengaturan analog DInput
Disable D-Pad diagonals (4-way touch) = Matikan D-Pad diagonal (sentuhan 4 arah)
Disable diagonal input = Nonaktifkan masukan diagonal
Double tap = Ketuk dua kali
Enable gesture control = Aktifkan kontrol gerakan
Enable standard shortcut keys = Aktifkan tombol pintas standar
Gesture = Gerak
Gesture mapping = Pemetaan gerakan
Glowing borders = Pinggiran bercahaya
HapticFeedback = Umpan balik (getar)
Hide touch analog stick background circle = Sembunyikan lingkaran latar belakang tongkat analog sentuh
Icon = Ikon
Ignore gamepads when not focused = Abaikan gamepad saat tidak fokus
Ignore Windows Key = Abaikan tombol Windows
Invert Axes = Balikkan sumbu
Invert Tilt along X axis = Balikkan kemiringan sepanjang sumbu X
Invert Tilt along Y axis = Balikkan kemiringan sepanjang sumbu Y
Keep this button pressed when right analog is pressed = Terus tekan tombol ini saat analog kanan ditekan
Keyboard = Papan ketik
L/R Trigger Buttons = Tombol pemicu L/R
Landscape = Lanskap
Landscape Auto = Lanskap otomatis
Landscape Reversed = Lanskap terbalik
Low end radius = Radius kelas atas
Mouse = Pengaturan Mouse
Mouse sensitivity = Sentivitas Mouse
Mouse smoothing = Kehalusan Mouse
MouseControl Tip = Anda sekarang dapat memetakan mouse di layar pemetaan kontrol dengan menekan ikon 'M'.
None (Disabled) = Tidak ada (nonaktif)
Off = Mati
OnScreen = Kontrol sentuh di layar
Portrait = Tegak
Portrait Reversed = Tegak terbalik
PSP Action Buttons = Tombol aksi PSP
Raw input = Masukan mentah
Reset to defaults = Setel ulang ke pengaturan awal
Screen aligned to ground = Layar sejajar kebawah
Screen at right angle to ground = Layar pada sudut kanan kebawah
Screen Rotation = Rotasi layar
seconds, 0 : off = detik, 0 = mati
Sensitivity (scale) = Sensivitas (skala)
Sensitivity = Sensitivitas
Shape = Membentuk/bentuk
Show right analog = Tampilkan analog kanan
Show Touch Pause Menu Button = Tampilkan tombol menu jeda
Swipe = Geser
Swipe sensitivity = Geser sensivitas
Swipe smoothing = Geser kehalusan
Thin borders = Garis batas tipis
Tilt Base Radius = Radius kemiringan dasar
Tilt Input Type = Jenis masukan kemiringan
Tilt Sensitivity along X axis = Sensitivitas kemiringan sepanjang sumbu X
Tilt Sensitivity along Y axis = Sensitivitas kemiringan sepanjang sumbu Y
To Calibrate = Untuk mengkalibrasi, taruh perangkat di permukaan datar dan tekan "Kalibrasi".
Toggle mode = Mode beralih
Touch Control Visibility = Visibilitas kontrol sentuh
Use custom right analog = Gunakan analog kanan kustom
Use Mouse Control = Gunakan kontrol mouse
Visibility = Visibilitas
Visible = Visibel
X = X
X + Y = X + Y
XInput Analog Settings = Pengaturan analog XInput
Y = Y

[CwCheats]
Cheats = Pengecoh
Edit Cheat File = Edit berkas pengecoh
Enable/Disable All = Hidupkan/matikan semua pengecoh
Import Cheats = Impor dari cheat.db
Options = Pilihan
Refresh Rate = Perbarui Penyegaran

[DesktopUI]
# If your language does not show well with the default font, you can use Font to specify a different one.
# Just add it to your language's ini file and uncomment it (remove the # by Font).
#Font = Trebuchet MS
About PPSSPP... = Tent&ang PPSSPP...
Auto = Otomatis
Auto Max Quality = Otomatis kualitas maksimum
Backend = Bangun Pelukisan &Penata Grafis(Mulai ulang PPSSPP)
Bicubic = &Bikubik
Break = Rusak
Break on Load = Rusak pada pemuatan
Buffered Rendering = Pelukisan Tersangga
Buy Gold = Beli versi &Gold
Control Mapping... = Pemetaan K&ontrol...
Debugging = Awakutu
Deposterize = &Deposterisasi
Direct3D9 = &Direct3D9
Direct3D11 = Direct3D11
Disassembly = &Pembongkaran...
Discord = Discord
Display Layout Editor = Penyunting tata letak tampilan...
Display Rotation = Rotasi tampilan
Dump Next Frame to Log = B&uang Laju Bingkai Berikutnya untuk Masuk
Emulation = &Emulasi
Enable Chat = Aktifkan pesan
Enable Cheats = Hidupkan Penge&coh
Enable Sound = Hidupkan Suara
Exit = Keluar
Extract File... = Ekstrak Berkas...
File = Berkas
Frame Skipping = &Lewati Laju Bingkai
Frame Skipping Type = Jenis Lewati Laju Bingkai
Fullscreen = &Layar Penuh
Game Settings = Pengaturan Permainan
GE Debugger... = Awakutu GE...
GitHub = Git&Hub
Hardware Transform = Transformasi Perangkat Keras
Help = Bantuan
Hybrid = &Hibrida
Hybrid + Bicubic = Hibrida + Bikubik
Ignore Illegal Reads/Writes = Aba&ikan Pembacaan/Penulisan Ilegal
Ignore Windows Key = Abaikan Tombol Windows
Keep PPSSPP On Top = Tahan PPSSPP di Atas
Landscape = Lanskap
Landscape reversed = Lanskap terbalik
Language... = Bahasa...
Linear = &Linier
Load = Muat...
Load .sym File... = Mu&at Berkas .sym...
Load Map File... = Muat Berkas &Map...
Load State = L&oad State
Load State File... = &Load State File...
Log Console = Konso&l Pencatat
Memory View... = Tampilan Memori...
More Settings... = Pengaturan Lainnya...
Nearest = Terdekat
Non-Buffered Rendering = Lewati efek penyangga (tak-tersangga, lebih cepat)
Off = Mati
Open Chat = Buka opsi pesan
Open Directory... = Buka &Direktori...
Open from MS:/PSP/GAME... = Buka dari MS:/PSP/GAME...
Open Memory Stick = Buka &Memory Stick
Open New Instance = Buka contoh baru
OpenGL = &OpenGL
Pause = Jeda
Pause When Not Focused = Jeda Ketika Tidak Fokus
Portrait = Tegak
Portrait reversed = Tegak terbalik
Postprocessing Shader = Postprocessin&g Shader
PPSSPP Forums = &Forum PPSSPP
Record = Rekam
Record Audio = Rekam Suara
Record Display = Rekam Tampilan
Rendering Mode = M&ode Pelukisan
Rendering Resolution = &Resolusi Pelukisan
Reset = Atur Ulang
Reset Symbol Table = Atur Ulang Tabel Simbol
Run = Jalankan
Save .sym File... = Simpan B&erkas .sym...
Save Map File... = &Simpan Berkas Peta...
Save State = Simp&an Posisi
Save State File... = &Simpan Berkas Posisi...
Savestate Slot = Simp&an Status Slot
Screen Scaling Filter = Penyaring P&enskala Layar
Show Debug Statistics = Tampilkan Statistik Awakutu
Show FPS Counter = Tampilkan Penghitung &FPS
Skip Number of Frames = Lewati nomor laju bingkai
 [...]