GPU: Avoid clears for non-simple depth values
hrydgard/ppsspp pull request #16361
Opened 2022-11-08 06:10 UTC by unknownbrackets

See #12626 and #14223.  This makes some related changes.

First, it avoids using a "true" clear when depth is not 0.0 or 1.0 *if* the game has ever used an equal comparison for depth.  This avoids rounding inaccuracies between the clear and draw paths in drivers, i.e. such as in #12626.  I'm not sure this fixes that bug, but I'm hopeful based on what's seen.

Note that this is conceptually similar to the "rebuilding jit with rounding mode checks", where we use the more optimal path if possible.

Next, because the above makes doing this safer, this also prefers a scaled depth range to in-shader depth rounding when 24-bit depth is used (practically always.)  This should be significantly faster for games that need per-pixel rounding (i.e. #14223), although it probably makes the #16015 workaround less usable.

Because a scaled range will never use 0/1, this does also mean that rounded depth with equality will never use clears, which probably has a penalty.  But it's probably made up for by not rounding in the shader.

As an attempt to improve the impact to #16015... I noticed multiple games in that list were using ineffective ALWAYS depth tests and tried forcing it off in that case.  I'm not sure it'll help but it doesn't seem like a bad thing.

-[Unknown]

2022-11-08 08:23 UTC, hrydgard commented
Hm, I thought LEQUAL/GEQUAL were super common, is it really worth having a separate mode?

2022-11-08 13:59 UTC, unknownbrackets commented
Well, they're relatively common (as is rounding mode in CPU), but there are definitely plenty of games that just use `>` or `<` throughout.  I didn't want to penalize them.

-[Unknown]

2022-11-08 17:04 UTC, hrydgard requested changes

2022-11-09 04:08 UTC, unknownbrackets commented on GPU/D3D11/GPU_D3D11.cpp
>  	}
Well, I'll just keep them different for now.  I was worrying that we've made vertex shaders overly complex from that other driver bug (that turned out to be the switch on unsigned), and figured that the range scaling is probably both faster and less likely to cause equal mismatches.

But we can leave it just to pixel for now, and I'll leave vertex alone.

-[Unknown]

2022-11-09 08:56 UTC, hrydgard approved these changes

2022-11-09 08:57 UTC, merged

2022-11-10 03:59 UTC, Gamemulatorer commented
This broke Nayuta graphics using vulkan backend.

https://user-images.githubusercontent.com/37603562/200997456-97899d06-f244-439a-9bc0-c0a73533bfb4.mp4

2022-11-10 04:05 UTC, unknownbrackets commented
Can you upload a frame dump of where it has a trail like that?

-[Unknown]

2022-11-10 04:22 UTC, Gamemulatorer commented
here we go 
[NPJH50625.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9977302/NPJH50625.ppdmp.zip)