ClientConfigSubscriber added
hrydgard/ppsspp pull request #17539
Opened 2023-05-31 18:15 UTC by Nemoumbra

Ok, now that the WebsocketClientInfo has been dealt with, here comes the second part.
This is a direct continuation of this (now closed) PR: https://github.com/hrydgard/ppsspp/pull/17388
The differences between my older code and this one are merely aesthetical (more comments + a slight style change in one place).

Unknownbrackets has recently expressed their concerns about whether the change makes it harder for contributors to add new broadcasters.
Well, let's think about it... Currently a programmer needs to add two new files (hpp and cpp with the broadcaster implementation) and register them in all the build scripts and project structure files, then create an instance of said broadcaster in the function `HandleDebuggerRequest` (WebSocket.cpp) and call `instance_name.Broadcast(ws)`.
After the proposed change it will also be necessary to add the name to the WebSocketClientInfo constructor (and that's easy to find because the map needs to be initialized somewhere and the new name is obviously not there by default) and surround the call with the check.

> One example would simply be fixing the bool values. If the default was false and it was zero-initialized, that'd be one less place to remember to change to have a correct implementation. The goal with things like this should be easy for "Nemoumbra from 6 months in the future" or "unknownbrackets from 6 months in the future" to write correct code. We silly humans tend to miss things when they are spread out in multiple places.

Exactly. Yet... the bool values are not default-initialized in my code! If you have some other notes, please tell me.

Note: I've just noticed how the GPU stat feed is implemented... Of course, I'm not considering configuring all the potential broadcasting subscribers. I don't even know if that's an architectural misstep, but it came as a surprise to me that the subscribers can broadcast.

2023-06-01 00:18 UTC, unknownbrackets requested changes
It's best to keep related code together and unrelated code apart.  This still doesn't address my feedback, please see the previous feedback again.

-[Unknown]

2023-06-01 15:53 UTC, Nemoumbra commented
I've reduced the additional number of files you have to edit to 0 (the initialization code was moved from the constructor closer to where the broadcasters are defined).

2023-06-04 04:55 UTC, unknownbrackets commented
Well, that's a little improvement, and at least there's a comment.  But why is it that it's important to maintain more places to repeat the same list of keys?

Overall, I'd really prefer that things were self-contained instead of crossing responsibilities like this.  It seems like your main hold-up is that you don't like that logging always sends messages, so it would be simpler and I'd be less stringent on a change that just did that.  I wouldn't really care much if there was just an event that requested pausing (or filtering, even) logging.  That could be useful for some cases, i.e. to say "I only want warnings."  As compared to filtering game events, that seems like it could be used to offload filter controls to the server (which might be sensible.)

If you want it to be global and for all APIs, understand that I'm asking for it not to be "paperwork" to create any new API.  Because all that means is that things will be missed.  Someone won't realize that they need to add the value in all these different places, and so it just won't work.  The goal should be making it easier to have less bugs in the future.

It's still not clear to me how it's beneficial to use `// Default them all on` and `at()` rather than a `disallowed` list that default-initializes to false (allowed.)  That seems more foolproof and more likely to Just Work.

I can see pros and cons on using keys in a map, but if we're going to use keys and not default initialize, shouldn't we make the APIs automatically support all keys?  Instead of adding `json.writeBool("another", allowed_config.at("another"));`?  Right now, because it requires manual initialization (but always happens), it's effectively the same as a struct would be, but just less typo safe because a typo in a key would still compile.

-[Unknown]

2023-06-13 15:49 UTC, Nemoumbra commented
The last review made me realize I somehow have read this wrong:
> If the default was false and it was zero-initialized, that'd be one less place to remember to change to have a correct implementation.

I thought you criticized the "default init == false" method (maybe my brain processed "less" as "more" somehow). 
This is why I was boasting about my code not doing this. I completely agree now that these were the bad parts. The current implementation uses operator() which creates the nodes the first time the loop [here](https://github.com/hrydgard/ppsspp/pull/17539/commits/3fbaea3b9a7f3e239906a5ac6956a5dea89d2fcd#diff-ea0f0facce693db696b68e2c2e16bf2364cc0e7e0d7a2c608369ac66f15db29fL197) is executed.

When it comes to structs... Using a struct may be better in some places, but it will make [this part](https://github.com/hrydgard/ppsspp/pull/17539/files#diff-013d3bc3b58fada0561d8579fe80d256fbd09efa1bd5922ed199dd0ba459e7b2R83) uglier, for instance. After all, we don't have named member access in runtime so... But if we want to care about the typos in compile-time, I think we can use enums. If you don't mind and don't see any other significant problems with this code, I can start implementing that.

2023-06-16 13:49 UTC, unknownbrackets approved these changes
Alright, this is fine.

-[Unknown]

2023-06-16 13:49 UTC, unknownbrackets commented on Core/Debugger/WebSocket/ClientConfigSubscriber.cpp
> +// Copyright (c) 2018- PPSSPP Project.
nit: Copyright years are probably a copy/paste error.

-[Unknown]

2023-06-16 15:20 UTC, merged