Adding PPSSPP logo (original and gold)
hrydgard/ppsspp pull request #18726
Opened 2024-01-19 09:41 UTC by indra87g

And also, I made bold text for your name (Henrik Rydgård)

2024-01-19 09:42 UTC, indra87g commented
Hope you accept it

2024-01-19 10:39 UTC, Florin9doi commented on README.md
> +<a href="https://imgbb.com/"><img src="https://i.ibb.co/gPybnRP/pngwing-com.png" alt="PPSSPP Original Logo" width="128" height="128"></a>
```suggestion
<img src="source_assets/image/icon_regular.png" alt="PPSSPP Original Logo" width="128" height="128">
<img src="source_assets/image/icon_gold.png" alt="......
```

The images are already present in this repo, there is no need to mirror them

2024-01-19 13:13 UTC, hrydgard commented on README.md
> +Created by **Henrik Rydgård**
don't really need my name bolded :)

2024-02-13 11:28 UTC, LethalManBoob commented
do not redeem this

2024-02-14 11:00 UTC, sneedsfeed1488 commented
sars you bully little kid
accept the indra
sar

2024-02-14 18:15 UTC, Fijxu commented
what?

2024-06-19 01:16 UTC, sandboxgamedev123 approved these changes

2024-06-19 01:16 UTC, sandboxgamedev123 commented on README.md
> +<a href="https://imgbb.com/"><img src="https://i.ibb.co/8mFD49P/pngwing-com-1.png" alt="PPSSPP Gold Logo - Buy Now !" border="0" width="128" height="128"></a>
```suggestion
```

2024-06-19 01:16 UTC, sandboxgamedev123 commented on README.md
> +<a href="https://imgbb.com/"><img src="https://i.ibb.co/8mFD49P/pngwing-com-1.png" alt="PPSSPP Gold Logo - Buy Now !" border="0" width="128" height="128"></a>
I recommend one logo. In this case, the regular logo.

2024-06-19 01:19 UTC, sandboxgamedev123 approved these changes

2024-06-19 01:28 UTC, sandboxgamedev123 requested changes

2024-06-19 01:28 UTC, sandboxgamedev123 commented on README.md
> +<a href="https://imgbb.com/"><img src="https://i.ibb.co/8mFD49P/pngwing-com-1.png" alt="PPSSPP Gold Logo - Buy Now !" border="0" width="128" height="128"></a>
```suggestion
```
If this pull request is merged, I would recommend one logo. In this case, the regular logo.

2024-06-19 01:51 UTC, sandboxgamedev123 reviewed
There is no comment regarding the approval of the pull request. I am not approving the pull request.

2024-06-19 02:05 UTC, sandboxgamedev123 requested changes
There is no comment regarding the approval of the pull request. I do not know if there is a way to remove previous approvals.

2024-09-17 13:29 UTC, closed without merging