minor fixes
hrydgard/ppsspp pull request #9165
Opened 2016-12-16 01:44 UTC by latot

Hi, again other minor fixes, principally overflows.

2016-12-18 18:13 UTC, hrydgard requested changes

2016-12-18 18:13 UTC, hrydgard commented on ext/native/util/random/rng.h
> -	uint32_t R32() {
This intentionally clips the value to 32 bits.

A way that might avoid the warning might be:

    return (uint32_t)((m_z << 16) + m_w); 

perhaps. Or 

    return ((m_z << 16) + m_w) & 0xFFFFFFFF

Either way, it's hardly important and I would prefer to just revert the changes made to this file.

2016-12-18 18:13 UTC, hrydgard commented on Core/CoreTiming.cpp
> +        ne->time += cyclesIntoFuture;
I don't think this change is worth making. The old code is clear and doesn't actually have any problems.

2016-12-18 19:50 UTC, latot commented on Core/CoreTiming.cpp
> +        ne->time += cyclesIntoFuture;
mm, hi, the problem here is for some reason values handled with this plus send an overflow, so it makes this undefined, that is the problem, but why works with this change and not with the old code i don't know.

2016-12-19 04:36 UTC, latot commented
Hi, i update some code following your advice, only as a note, ub(undefined behavior) don't are warning are bugs, and can be caused for a human error, or some hardware limits and similars, i think need to be fixed.

2017-02-18 16:28 UTC, closed without merging