Implemented sceUtilityGetSystemParamInt
hrydgard/ppsspp pull request #9582
Opened 2017-04-09 12:03 UTC by sum2012

Colin McRae Rally 2005+ use it.

Do we need to create g_config.ADHOC_CHANNEL ?

2017-04-09 14:42 UTC, unknownbrackets requested changes

2017-04-09 14:42 UTC, unknownbrackets commented on Core/HLE/sceUtility.cpp
> +	{0X45C18506, &WrapU_UU<sceUtilityGetSystemParamInt_>,          "sceUtilitySetSystemParamInt",            'x', "xx"   },
Why did you name it Get when it's Set?

-[Unknown]

2017-04-09 14:42 UTC, unknownbrackets commented on Core/Dialog/PSPDialog.h
> +const int ERROR_UTILITY_INVALID_SYSTEM_PARAM_ID = 0x80110103;
Is there a reason to have no SCE_ prefix on these?

-[Unknown]

2017-04-09 14:42 UTC, unknownbrackets commented on Core/HLE/sceUtility.cpp
> +	        switch (id) {
A lot of these lines use spaces for indentation.

I recommend installing editorconfig:
https://marketplace.visualstudio.com/items?itemName=EditorConfigTeam.EditorConfig

And then simply reindent this section.  Tabs for indent, spaces for alignment.

-[Unknown]

2017-04-09 14:46 UTC, sum2012 commented on Core/HLE/sceUtility.cpp
> +	{0X45C18506, &WrapU_UU<sceUtilityGetSystemParamInt_>,          "sceUtilitySetSystemParamInt",            'x', "xx"   },
There is a another function same name ,so I add _

2017-04-09 14:46 UTC, sum2012 commented on Core/Dialog/PSPDialog.h
> +const int ERROR_UTILITY_INVALID_SYSTEM_PARAM_ID = 0x80110103;
Copy from jpcsp source

2017-04-09 17:41 UTC, hrydgard commented on Core/HLE/sceUtility.cpp
> +	        switch (id) {
Tip: Can autoindent the selected code with Ctrl+K, Ctrl+F .

2017-04-10 12:28 UTC, sum2012 commented on Core/HLE/sceUtility.cpp
> +	        switch (id) {
@hrydgard Very Thanks tip

2017-04-10 12:35 UTC, sum2012 commented
done

2017-06-06 17:11 UTC, hrydgard commented
Fixed the get/set confusion and merged manually, so closing.

2017-06-06 17:11 UTC, closed without merging

2017-06-07 23:17 UTC, sum2012 commented
oop,thanks