Quick hack to enable analog stick sensitivity on non-windows platforms.
hrydgard/ppsspp pull request #9677
Opened 2017-05-10 12:31 UTC by hrydgard

See #8028.

Not really happy with this though as we should instead move sensitivity processing to when we are putting together the struct for the PSP to read, and not in the input layer as it is currently.

2017-05-10 13:10 UTC, InusualZ reviewed
Instead of doing the multiplication everytime you assign the var, why you don't try to apply the value when the variable is used, I really don't have any idea if it's possible.

2017-05-10 13:12 UTC, InusualZ commented on android/jni/app-android.cpp
> +	axis.value *= sensitivity;
Why you don't this operation directly with the Config member?

2017-05-10 13:37 UTC, hrydgard commented on android/jni/app-android.cpp
> +	axis.value *= sensitivity;
I started typing thinking I was going to multiply two axis with the value I guess, but there was only one. Doesn't really matter.

2017-05-10 14:34 UTC, hrydgard commented
@InusualZ That's what the pull request comment says, but that would be a bigger change. Also I think the sensitivity config needs a rethink or at least a renaming, and it should be combined with a preview like the current joystick checker on a separate screen, probably.

2017-05-10 19:26 UTC, InusualZ commented
Ohh sorry, I miss that :/

2017-05-11 03:48 UTC, unknownbrackets requested changes
Well, I think it's not that terrible to do it on input - although this also skips DirectX, right?

It probably would just go here if it was in sceCtrl:
https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceCtrl.cpp#L186

This is actually still on touch, though.  I think it's mostly simpler this way, but it could be moved to CtrlUpdateLatch.

-[Unknown]

2017-05-11 03:48 UTC, unknownbrackets commented on Core/Config.h
> +
Hm?

-[Unknown]

2017-05-11 03:48 UTC, unknownbrackets commented on UI/GameSettingsScreen.cpp
> +#ifdef d_WIN32
Oops.

-[Unknown]

2017-05-11 06:06 UTC, hrydgard commented on UI/GameSettingsScreen.cpp
> +#ifdef d_WIN32
my wireless keyboard has been acting up, heh.

2017-05-18 13:47 UTC, hrydgard commented
Yeah, you're right that we don't want to affect input from touch.

I think this is probably good enough for 1.4.1 now. A bigger redesign is for a later point release. Can I merge?

2017-05-20 17:41 UTC, unknownbrackets approved these changes

2017-05-20 17:41 UTC, merged