Unify some code in DrawEngine
hrydgard/ppsspp pull request #9770
Opened 2017-06-02 11:09 UTC by hrydgard

2017-06-02 16:57 UTC, unknownbrackets requested changes

2017-06-02 16:57 UTC, unknownbrackets commented on GPU/Common/DrawEngineCommon.cpp
> +
nit: Spacious.

-[Unknown]

2017-06-02 16:57 UTC, unknownbrackets commented on GPU/Common/IndexGenerator.cpp
> +	if (sizeof(ITypeLE) == sizeof(inds[0]) && indexOffset == 0) {
Hmm, isn't that by definition `const ITypeLE *inds`?  Should be `inds_`.

-[Unknown]

2017-06-02 21:52 UTC, hrydgard commented on GPU/Common/IndexGenerator.cpp
> +	if (sizeof(ITypeLE) == sizeof(inds[0]) && indexOffset == 0) {
Eh, yes :) Thanks.

2017-06-03 16:43 UTC, merged

2017-06-03 16:43 UTC, hrydgard commented
Fixed the commented things, rebased and merged.